---
name: Heapviz tool tests
on:
  push:
    paths:
      - 'tools/heapviz/**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  heapviz_test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install ncurses
        run: sudo apt-get install libncurses-dev

      - name: Check heapviz tool
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path tools/heapviz/Cargo.toml

      - name: Unit testing of heapviz tool (debug mode)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path tools/heapviz/Cargo.toml

      - name: Unit testing of heapviz tool (release mode)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path tools/heapviz/Cargo.toml --release
