---
name: OpenSK build
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_ctap2:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up submodules
        run: ./setup-submodules.sh
      - uses: actions-rs/toolchain@v1
        with:
          target: thumbv7em-none-eabi
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Set up OpenSK
        run: ./setup.sh

      - name: Building sha256sum tool
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path third_party/tock/tools/sha256sum/Cargo.toml

      - name: Building OpenSK
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=thumbv7em-none-eabi --features with_ctap1
      - name: Compute SHA-256 sum
        run: ./third_party/tock/tools/sha256sum/target/debug/sha256sum target/thumbv7em-none-eabi/release/ctap2
