---
name: OpenSK tests
on:
  push:
    paths:
      - 'src/**/*.rs'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ctap2_test:
    name: CTAP2 unit tests
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        cargo_features: [std std,with_ctap1]

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          target: thumbv7em-none-eabi
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Set up OpenSK
        run: ./setup.sh

      - name: Unit testing of CTAP2 (release mode)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --features ${{ cargo_features }}

      - name: Unit testing of CTAP2 (debug mode)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features ${{ cargo_features }}
